# Overall settings:
batch_size: 4
lr: 0.01
momentum: 0.9
tensorboard_path: tboard
num_epochs: 12
num_colors: 9

# Posterior cortex settings:
num_pretrain_epochs: 3
posterior_input_dim: 19200
posterior_hidden_dim: 1000
posterior_output_dim: 300

# Prefrontal cortex settings:
num_stripes:
  - 10
  - 12
stripe_dim:
  - 7
  - 3
alpha:
  - 0.2
  - 0.2

# Basal ganglia settings:
gamma: 0.5
iter_before_train: 200
eps: 0.2
memory_buffer_size: 1000
replace_every_n: 30
log_every_n: 5
